spring:
  profiles:
    active: docker

  jackson:
    time-zone: Asia/Kolkata

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata

server:
  port: 8080

management:
  health:
    defaults:
      enabled: true

    elasticsearch:
      enabled: true

  endpoint:
    health:
      show-details: always
      validate-group-membership: false
      group:
        liveness:
          include: ping
        readiness:
          include: db

  endpoints:
    web:
      exposure:
        include: health,info, mappings
